apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d0immaeaz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d0immaeaz-go 
  name: d0immaeaz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d0immaeaz-go 
